/* Copyright 2025 Raphael Outhier - confidential - proprietary - no copy - no diffusion. */

/*
 * Regular currencies.
 */
TB_CCY("Afghan afghani", AFN)
TB_CCY("Albanian lek", ALL)
TB_CCY("Armenian dram", AMD)
TB_CCY("Angolan kwanza", AOA)
TB_CCY("Argentine peso", ARS)
TB_CCY("Australian dollar", AUD)
TB_CCY("Aruban florin", AWG)
TB_CCY("Azerbaijani manat", AZN)
TB_CCY("Bahamian dollar", BSD)
TB_CCY("Bahraini dinar", BHD)
TB_CCY("Bangladeshi taka", BDT)
TB_CCY("Barbadian dollar", BBD)
TB_CCY("Belarusian ruble", BYN)
TB_CCY("Bosnia and Herzegovina convertible mark", BAM)
TB_CCY("Botswana pula", BWP)
TB_CCY("Brazilian real", BRL)
TB_CCY("Brunei dollar", BND)
TB_CCY("Bulgarian lev", BGN)
TB_CCY("Burundian franc", BIF)
TB_CCY("Canadian dollar", CAD)
TB_CCY("CFA franc BCEAO", XOF)
TB_CCY("CFA franc BEAC", XAF)
TB_CCY("Chilean peso", CLP)
TB_CCY("Chinese yuan", CNY)
TB_CCY("Colombian peso", COP)
TB_CCY("Congolese franc", CDF)
TB_CCY("Costa Rican colon", CRC)
TB_CCY("Cuban peso", CUP)
TB_CCY("Czech koruna", CZK)
TB_CCY("Danish krone", DKK)
TB_CCY("Djiboutian franc", DJF)
TB_CCY("Dominican peso", DOP)
TB_CCY("Egyptian pound", EGP)
TB_CCY("Ethiopian birr", ETB)
TB_CCY("Euro", EUR)
TB_CCY("Fijian dollar", FJD)
TB_CCY("Ghanaian cedi", GHS)
TB_CCY("Gibraltar pound", GIP)
TB_CCY("Guatemalan quetzal", GTQ)
TB_CCY("Guinean franc", GNF)
TB_CCY("Guyana dollar", GYD)
TB_CCY("Haitian gourde", HTG)
TB_CCY("Honduran lempira", HNL)
TB_CCY("Hong Kong dollar", HKD)
TB_CCY("Hungarian forint", HUF)
TB_CCY("Icelandic króna", ISK)
TB_CCY("Indian rupee", INR)
TB_CCY("Indonesian rupiah", IDR)
TB_CCY("Iranian rial", IRR)
TB_CCY("Iraqi dinar", IQD)
TB_CCY("Israeli new shekel", ILS)
TB_CCY("Jamaican dollar", JMD)
TB_CCY("Japanese yen", JPY)
TB_CCY("Jordanian dinar", JOD)
TB_CCY("Kazakhstani tenge", KZT)
TB_CCY("Kenyan shilling", KES)
TB_CCY("Kuwaiti dinar", KWD)
TB_CCY("Kyrgyzstani som", KGS)
TB_CCY("Laotian kip", LAK)
TB_CCY("Lebanese pound", LBP)
TB_CCY("Lesotho loti", LSL)
TB_CCY("Liberian dollar", LRD)
TB_CCY("Libyan dinar", LYD)
TB_CCY("Macanese pataca", MOP)
TB_CCY("Malagasy ariary", MGA)
TB_CCY("Malawian kwacha", MWK)
TB_CCY("Malaysian ringgit", MYR)
TB_CCY("Maldivian rufiyaa", MVR)
TB_CCY("Mauritanian ouguiya", MRU)
TB_CCY("Mauritian rupee", MUR)
TB_CCY("Mexican peso", MXN)
TB_CCY("Mongolian tögrög", MNT)
TB_CCY("Moroccan dirham", MAD)
TB_CCY("Mozambican metical", MZN)
TB_CCY("Myanmar kyat", MMK)
TB_CCY("Namibian dollar", NAD)
TB_CCY("Nepalese rupee", NPR)
TB_CCY("Nicaraguan córdoba", NIO)
TB_CCY("Nigerian naira", NGN)
TB_CCY("Norwegian krone", NOK)
TB_CCY("Omani rial", OMR)
TB_CCY("Pakistani rupee", PKR)
TB_CCY("Panamanian balboa", PAB)
TB_CCY("Papua New Guinean kina", PGK)
TB_CCY("Paraguayan guaraní", PYG)
TB_CCY("Peruvian sol", PEN)
TB_CCY("Philippine peso", PHP)
TB_CCY("Polish złoty", PLN)
TB_CCY("Qatari riyal", QAR)
TB_CCY("Romanian leu", RON)
TB_CCY("Russian ruble", RUB)
TB_CCY("Rwandan franc", RWF)
TB_CCY("Samoan tala", WST)
TB_CCY("São Tomé and Príncipe dobra", STN)
TB_CCY("Saudi riyal", SAR)
TB_CCY("Serbian dinar", RSD)
TB_CCY("Seychellois rupee", SCR)
TB_CCY("Sierra Leonean leone", SLL)
TB_CCY("Singapore dollar", SGD)
TB_CCY("Solomon Islands dollar", SBD)
TB_CCY("Somali shilling", SOS)
TB_CCY("South African rand", ZAR)
TB_CCY("South Sudanese pound", SSP)
TB_CCY("Sri Lankan rupee", LKR)
TB_CCY("Sudanese pound", SDG)
TB_CCY("Surinamese dollar", SRD)
TB_CCY("Swedish krona", SEK)
TB_CCY("Swiss franc", CHF)
TB_CCY("Syrian pound", SYP)
TB_CCY("Tajikistani somoni", TJS)
TB_CCY("Tanzanian shilling", TZS)
TB_CCY("Thai baht", THB)
TB_CCY("Tongan paʻanga", TOP)
TB_CCY("Trinidad and Tobago dollar", TTD)
TB_CCY("Tunisian dinar", TND)
TB_CCY("Turkish lira", TRY)
TB_CCY("Turkmenistan manat", TMT)
TB_CCY("Ugandan shilling", UGX)
TB_CCY("Ukrainian hryvnia", UAH)
TB_CCY("United Arab Emirates dirham", AED)
TB_CCY("United States dollar", USD)
TB_CCY("Uruguayan peso", UYU)
TB_CCY("Uzbekistani soʻm", UZS)
TB_CCY("Vanuatu vatu", VUV)
TB_CCY("Venezuelan bolívar soberano", VES)
TB_CCY("Vietnamese đồng", VND)
TB_CCY("Yemeni rial", YER)
TB_CCY("Zambian kwacha", ZMW)

/*
 * Crypto currencies.
 */
TB_CCY("Bitcoin", BTC)
TB_CCY("Ethereum", ETH)
TB_CCY("Tether", USDT)
TB_CCY("BNB", BNB)
TB_CCY("USD Coin", USDC)
TB_CCY("Solana", SOL)
TB_CCY("XRP", XRP)
TB_CCY("Dogecoin", DOGE)
TB_CCY("Cardano", ADA)
TB_CCY("TRON", TRX)
TB_CCY("Avalanche", AVAX)
TB_CCY("Polkadot", DOT)
TB_CCY("Chainlink", LINK)
TB_CCY("Litecoin", LTC)
TB_CCY("Stellar", XLM)
TB_CCY("Shiba Inu", SHIB)
TB_CCY("Wrapped Bitcoin", WBTC)
TB_CCY("Uniswap", UNI)
TB_CCY("Polygon", MATIC)
TB_CCY("Toncoin", TON)
TB_CCY("Hyperliquid", HYPE)
TB_CCY("Bitcoin Cash", BCH)
TB_CCY("Hedera", HBAR)
TB_CCY("Monero", XMR)
TB_CCY("Dai", DAI)
TB_CCY("Bitget Token", BGB)
TB_CCY("Ethereum Classic", ETC)
TB_CCY("Aave", AAVE)
TB_CCY("OKB", OKB)
TB_CCY("Near", NEAR)
TB_CCY("Aptos", APT)
TB_CCY("Worldcoin", WLD)
TB_CCY("Pi Network", PI)
TB_CCY("Bittensor", TAO)
TB_CCY("Arbitrum", ARB)
TB_CCY("Internet Computer", ICP)
TB_CCY("WhiteBIT Coin", WBT)
TB_CCY("Story", STORY)
TB_CCY("Pepe", PEPE)
TB_CCY("Ondo", ONDO)
TB_CCY("Sky Dollar", USDS)
TB_CCY("World Liberty Financial", WLFI)
TB_CCY("VeChain", VET)
TB_CCY("Cosmos", ATOM)
TB_CCY("Algorand", ALGO)
TB_CCY("KuCoin Token", KCS)
TB_CCY("Sei", SEI)
TB_CCY("Flare", FLR)
TB_CCY("Bonk", BONK)
TB_CCY("Render", RNDR)
TB_CCY("Immutable", IMX)
TB_CCY("XDC Network", XDC)
TB_CCY("GateToken", GT)
TB_CCY("Optimism", OP)
TB_CCY("PayPal USD", PYUSD)
TB_CCY("Injective", INJ)
TB_CCY("Celestia", TIA)
TB_CCY("Quant", QNT)
TB_CCY("Stacks", STX)
TB_CCY("Lido DAO", LDO)
TB_CCY("Curve DAO Token", CRV)
TB_CCY("PAX Gold", PAXG)
TB_CCY("Aerodrome Finance", AERO)
TB_CCY("PancakeSwap", CAKE)
TB_CCY("Kaia", KAIA)
TB_CCY("The Graph", GRT)
TB_CCY("DeXe", DEXE)
TB_CCY("Pyth Network", PYTH)
TB_CCY("Conflux", CFX)
TB_CCY("Theta Network", THETA)
TB_CCY("Gala", GALA)
TB_CCY("Tezos", XTZ)
TB_CCY("Zcash", ZEC)

